### ISSUE TITLE
Error Encountered When Selecting Purchase Invoice in Asset Repair

### ISSUE THREAD

**Issue by deepdoshi79** [8848digital/Assets#18]
Receiving the following error when selecting a purchase invoice for an asset repair doctype.
![image](https://github.com/user-attachments/assets/bf6331a6-6e12-4b70-9b1f-9c52a35f9dfe)
### App Versions
```
{
	"assets": "0.0.1",
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1"
}
```
### Route
```
Form/Asset Repair/new-asset-repair-pqemvizmaa
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/search.py", line 47, in search_link
    results = search_widget(
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/search.py", line 93, in search_widget
    is_whitelisted(frappe.get_attr(query))
  File "apps/frappe/frappe/__init__.py", line 1765, in get_attr
    return getattr(get_module(modulename), methodname)
  File "apps/frappe/frappe/__init__.py", line 1483, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'erpnext.assets.doctype.asset_repair.asset_repair'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"txt": "",
		"doctype": "Purchase Invoice",
		"ignore_user_permissions": 0,
		"reference_doctype": "Asset Repair Purchase Invoice",
		"page_length": 10,
		"query": "erpnext.assets.doctype.asset_repair.asset_repair.get_purchase_invoice",
		"filters": "{\"company\":\"PP Ltd\",\"docstatus\":1}"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.search.search_link",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "ModuleNotFoundError: No module named 'erpnext.assets.doctype.asset_repair.asset_repair'",
	"exc_type": "ModuleNotFoundError"
}
```

**Comment by tinadn** [comment]
Working fine. Hence closing.
