### ISSUE TITLE
Erron in test_asset_depreciation_on_sale_with_pro_rata

### ISSUE THREAD

**Issue by aartimanjare** [8848digital/Assets#31]
### Information about bug

ERROR: test_asset_depreciation_on_sale_with_pro_rata (erpnext.accounts.doctype.sales_invoice.test_sales_invoice.TestSalesInvoice)

### Module

accounts

### Version

Frappe - V15
Erpnext - V15

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
bench run-tests --doctype "Sales Invoice" --test test_asset_depreciation_on_sale_with_pro_rata
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/aarti/postgres/frappe-bench-post/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/aarti/postgres/frappe-bench-post/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aarti/postgres/frappe-bench-post/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aarti/postgres/frappe-bench-post/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/aarti/postgres/frappe-bench-post/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/env/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/commands/__init__.py", line 29, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/commands/utils.py", line 790, in run_tests
    ret = frappe.test_runner.main(
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/test_runner.py", line 88, in main
    ret = run_tests_for_doctype(
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/test_runner.py", line 214, in run_tests_for_doctype
    return _run_unittest(
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/test_runner.py", line 283, in _run_unittest
    out = runner.run(test_suite)
  File "/usr/lib/python3.10/unittest/runner.py", line 184, in run
    test(result)
  File "/usr/lib/python3.10/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.10/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.10/unittest/case.py", line 650, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/doctype/sales_invoice/test_sales_invoice.py", line 2963, in test_asset_depreciation_on_sale_with_pro_rata
    post_depreciation_entries(getdate("2021-09-30"))
  File "/home/aarti/postgres/frappe-bench-post/apps/assets/assets/assets/doctype/asset/depreciation.py", line 53, in post_depreciation_entries
    depreciable_asset_depr_schedules_data = get_depreciable_asset_depr_schedules_data(date)
  File "/home/aarti/postgres/frappe-bench-post/apps/assets/assets/assets/doctype/asset/depreciation.py", line 140, in get_depreciable_asset_depr_schedules_data
    res = res.run()
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/database/database.py", line 249, in sql
    traceback.print_stack()
'Error in query:\ncolumn "tabAsset.name" must appear in the GROUP BY clause or be used in an aggregate function\nLINE 1: SELECT "tabAsset Depreciation Schedule"."name","tabAsset"."n...\n                                                       ^\n'
E
======================================================================
ERROR: test_asset_depreciation_on_sale_with_pro_rata (erpnext.accounts.doctype.sales_invoice.test_sales_invoice.TestSalesInvoice)
Tests if an Asset set to depreciate yearly on June 30, that gets sold on Sept 30, creates an additional depreciation entry on its date of sale.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aarti/postgres/frappe-bench-post/apps/erpnext/erpnext/accounts/doctype/sales_invoice/test_sales_invoice.py", line 2963, in test_asset_depreciation_on_sale_with_pro_rata
    post_depreciation_entries(getdate("2021-09-30"))
  File "/home/aarti/postgres/frappe-bench-post/apps/assets/assets/assets/doctype/asset/depreciation.py", line 53, in post_depreciation_entries
    depreciable_asset_depr_schedules_data = get_depreciable_asset_depr_schedules_data(date)
  File "/home/aarti/postgres/frappe-bench-post/apps/assets/assets/assets/doctype/asset/depreciation.py", line 140, in get_depreciable_asset_depr_schedules_data
    res = res.run()
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/database/postgres/database.py", line 218, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "/home/aarti/postgres/frappe-bench-post/apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.GroupingError: column "tabAsset.name" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT "tabAsset Depreciation Schedule"."name","tabAsset"."n...
                                                       ^


----------------------------------------------------------------------
Ran 1 test in 0.897s

FAILED (errors=1)
```

**Comment by tinadn** [comment]
Issue resolved.
