### ISSUE TITLE
An error is occurring while attempting to split the asset.

### ISSUE THREAD

**Issue by deepdoshi79** [8848digital/Assets#55]
### Information about bug

An error is occurring while attempting to split the asset.
![image](https://github.com/user-attachments/assets/e419cd85-0f93-4d7b-8111-eff6732bea62)

### Module

assets

### Version

Assets: v0.0.1 (pre-prod)

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"assets": "0.0.1",
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1",
	"sales_commission": "0.0.1"
}
```
### Route
```
Form/Asset/ACC-ASS-2024-01988
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/assets/assets/assets/doctype/asset/asset.py", line 1147, in split_asset
    update_existing_asset(asset, remaining_qty, new_asset.name)
  File "apps/assets/assets/assets/doctype/asset/asset.py", line 1197, in update_existing_asset
    new_asset_depr_schedule_doc = frappe.copy_doc(current_asset_depr_schedule_doc)
  File "apps/frappe/frappe/__init__.py", line 1891, in copy_doc
    d = doc.as_dict()
AttributeError: 'NoneType' object has no attribute 'as_dict'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"asset_name": "ACC-ASS-2024-01988",
		"split_qty": 3
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/assets.assets.doctype.asset.asset.split_asset",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "AttributeError: 'NoneType' object has no attribute 'as_dict'",
	"exc_type": "AttributeError",
	"_exc_source": "assets (app)"
}
```
```

**Comment by tohidmalik002** [comment]
Fixed: https://github.com/8848digital/Assets/pull/64

**Comment by deepdoshi79** [comment]
Functionality Working. Issue Resolved
