### ISSUE TITLE
An error is occurring while attempting to sell the asset

### ISSUE THREAD

**Issue by deepdoshi79** [8848digital/Assets#56]
### Information about bug

An error is occurring while attempting to sell the asset. 
Reference Asset Item ACC-ASS-2024-01480
![image](https://github.com/user-attachments/assets/dc93a57f-a329-4874-8d16-4ddf4357fd68)

### Module

assets

### Version

Assets: v0.0.1 (pre-prod)

ERPNext: v15.34.0 (pre-prod)

Frappe Framework: v15.41.0 (pre-prod)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"assets": "0.0.1",
	"erpnext": "15.34.0",
	"frappe": "15.41.0",
	"payments": "0.0.1",
	"sales_commission": "0.0.1"
}
```
### Route
```
Form/Sales Invoice/ACC-SINV-2024-34771
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 37, in savedocs
    doc.submit()
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1048, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 1031, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 390, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1131, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 451, in on_submit
    self.make_gl_entries()
  File "apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 1155, in make_gl_entries
    gl_entries = self.get_gl_entries()
  File "apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 1202, in get_gl_entries
    self.make_item_gl_entries(gl_entries)
  File "apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 1354, in make_item_gl_entries
    depreciate_asset(asset, self.posting_date, notes)
  File "apps/assets/assets/assets/doctype/asset/depreciation.py", line 627, in depreciate_asset
    make_depreciation_entry_for_all_asset_depr_schedules(asset_doc, date)
  File "apps/assets/assets/assets/doctype/asset/depreciation.py", line 150, in make_depreciation_entry_for_all_asset_depr_schedules
    make_depreciation_entry(asset_depr_schedule_name, date)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/assets/assets/assets/doctype/asset/depreciation.py", line 276, in make_depreciation_entry
    asset.set_status()
  File "apps/assets/assets/assets/doctype/asset/asset.py", line 592, in set_status
    self.db_set("status", status)
  File "apps/frappe/frappe/model/document.py", line 1208, in db_set
    self.load_doc_before_save()
  File "apps/frappe/frappe/model/document.py", line 1112, in load_doc_before_save
    self._doc_before_save = frappe.get_doc(self.doctype, self.name, for_update=True)
  File "apps/frappe/frappe/__init__.py", line 1340, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 85, in get_doc
    return controller(*args, **kwargs)
  File "apps/erpnext/erpnext/controllers/accounts_controller.py", line 98, in __init__
    super().__init__(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 126, in __init__
    self.load_from_db()
  File "apps/frappe/frappe/model/document.py", line 167, in load_from_db
    d = frappe.db.get_value(
  File "apps/frappe/frappe/database/database.py", line 512, in get_value
    result = self.get_values(
  File "apps/frappe/frappe/database/database.py", line 616, in get_values
    out = self._get_values_from_table(
  File "apps/frappe/frappe/database/database.py", line 889, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "apps/frappe/frappe/database/postgres/database.py", line 310, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 227, in sql
    self._cursor.execute(query, values)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":\"ACC-SINV-2024-34770\",\"owner\":\"Administrator\",\"creation\":\"2024-11-04 12:41:12.391122\",\"modified\":\"2024-11-04 12:41:12.391122\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":0,\"title\":\"Pooja S\",\"naming_series\":\"ACC-SINV-.YYYY.-\",\"customer\":\"8848\",\"customer_name\":\"Pooja S\",\"tax_id\":null,\"company\":\"8848 Digital\",\"company_tax_id\":null,\"posting_date\":\"2024-11-04\",\"posting_time\":\"12:41:12.467090\",\"set_posting_time\":0,\"due_date\":\"2024-11-04\",\"is_pos\":0,\"pos_profile\":null,\"is_consolidated\":0,\"is_return\":0,\"return_against\":null,\"update_outstanding_for_self\":1,\"update_billed_amount_in_sales_order\":0,\"update_billed_amount_in_delivery_note\":1,\"is_debit_note\":0,\"amended_from\":null,\"location\":null,\"cost_center\":null,\"department\":null,\"project\":null,\"currency\":\"INR\",\"conversion_rate\":1,\"selling_price_list\":\"Standard Selling\",\"price_list_currency\":\"INR\",\"plc_conversion_rate\":1,\"ignore_pricing_rule\":0,\"scan_barcode\":null,\"update_stock\":0,\"set_warehouse\":null,\"set_target_warehouse\":null,\"total_qty\":1,\"total_net_weight\":0,\"base_total\":10000,\"base_net_total\":10000,\"total\":10000,\"net_total\":10000,\"exempt_from_sales_tax\":0,\"tax_category\":\"Reverse Charge In-State\",\"taxes_and_charges\":null,\"shipping_rule\":null,\"incoterm\":null,\"named_place\":null,\"base_total_taxes_and_charges\":0,\"total_taxes_and_charges\":0,\"base_grand_total\":10000,\"base_rounding_adjustment\":0,\"base_rounded_total\":0,\"base_in_words\":\"\",\"grand_total\":10000,\"rounding_adjustment\":0,\"use_company_roundoff_cost_center\":0,\"rounded_total\":0,\"in_words\":\"\",\"total_advance\":0,\"outstanding_amount\":10000,\"disable_rounded_total\":1,\"apply_discount_on\":\"Grand Total\",\"base_discount_amount\":0,\"is_cash_or_non_trade_discount\":0,\"additional_discount_account\":null,\"additional_discount_percentage\":0,\"discount_amount\":0,\"other_charges_calculation\":null,\"total_billing_hours\":0,\"total_billing_amount\":0,\"cash_bank_account\":null,\"base_paid_amount\":0,\"paid_amount\":0,\"base_change_amount\":0,\"change_amount\":0,\"account_for_change_amount\":null,\"allocate_advances_automatically\":0,\"only_include_allocated_payments\":0,\"write_off_amount\":0,\"base_write_off_amount\":0,\"write_off_outstanding_amount_automatically\":0,\"write_off_account\":null,\"write_off_cost_center\":null,\"redeem_loyalty_points\":0,\"loyalty_points\":0,\"loyalty_amount\":0,\"loyalty_program\":\"new year\",\"loyalty_redemption_account\":null,\"loyalty_redemption_cost_center\":null,\"customer_address\":null,\"address_display\":null,\"contact_person\":null,\"contact_display\":null,\"contact_mobile\":null,\"contact_email\":null,\"territory\":\"All Territories\",\"shipping_address_name\":null,\"shipping_address\":null,\"dispatch_address_name\":null,\"dispatch_address\":null,\"company_address\":\"8848 Digital-Billing\",\"company_address_display\":\"address line1<br>\\naddress line1<br>mumbai<br>\\nMaharashtra<br>400078<br>India<br>\\n<br>\\n\",\"ignore_default_payment_terms_template\":0,\"payment_terms_template\":null,\"tc_name\":null,\"terms\":null,\"po_no\":\"\",\"po_date\":null,\"debit_to\":\"Debtors - 8D\",\"party_account_currency\":\"INR\",\"is_opening\":\"No\",\"unrealized_profit_loss_account\":null,\"against_income_account\":\"Gain/Loss on Asset Disposal - 8D\",\"sales_partner\":null,\"amount_eligible_for_commission\":10000,\"commission_rate\":0,\"total_commission\":0,\"letter_head\":null,\"group_same_items\":0,\"select_print_heading\":null,\"language\":\"en\",\"subscription\":null,\"from_date\":null,\"auto_repeat\":null,\"to_date\":null,\"status\":\"Draft\",\"inter_company_invoice_reference\":null,\"campaign\":null,\"represents_company\":null,\"source\":null,\"customer_group\":\"All Customer Groups\",\"is_internal_customer\":0,\"is_discounted\":0,\"remarks\":\"No Remarks\",\"doctype\":\"Sales Invoice\",\"items\":[{\"name\":\"90t4e74198\",\"owner\":\"Administrator\",\"creation\":\"2024-11-04 12:41:12.391122\",\"modified\":\"2024-11-04 12:41:12.391122\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":1,\"barcode\":null,\"has_item_scanned\":0,\"item_code\":\"Crane\",\"item_name\":\"Crane\",\"customer_item_code\":null,\"description\":\"Crane\",\"item_group\":\"_Test Item Group\",\"brand\":null,\"image\":\"\",\"qty\":1,\"stock_uom\":\"Nos\",\"uom\":\"Nos\",\"conversion_factor\":1,\"stock_qty\":1,\"price_list_rate\":0,\"base_price_list_rate\":0,\"margin_type\":\"\",\"margin_rate_or_amount\":0,\"rate_with_margin\":0,\"discount_percentage\":10,\"discount_amount\":0,\"base_rate_with_margin\":0,\"rate\":10000,\"amount\":10000,\"item_tax_template\":null,\"base_rate\":10000,\"base_amount\":10000,\"pricing_rules\":\"[\\n \\\"PRLE-0003\\\"\\n]\",\"stock_uom_rate\":10000,\"is_free_item\":0,\"grant_commission\":1,\"net_rate\":10000,\"net_amount\":10000,\"base_net_rate\":10000,\"base_net_amount\":10000,\"delivered_by_supplier\":0,\"income_account\":\"Gain/Loss on Asset Disposal - 8D\",\"is_fixed_asset\":1,\"asset\":\"ACC-ASS-2024-01480\",\"finance_book\":null,\"expense_account\":\"Cost of Goods Sold - 8D\",\"discount_account\":null,\"deferred_revenue_account\":null,\"service_stop_date\":null,\"enable_deferred_revenue\":0,\"service_start_date\":null,\"service_end_date\":null,\"weight_per_unit\":0,\"total_weight\":0,\"weight_uom\":null,\"warehouse\":\"Stores - 8D\",\"target_warehouse\":null,\"quality_inspection\":null,\"serial_and_batch_bundle\":null,\"use_serial_batch_fields\":1,\"allow_zero_valuation_rate\":0,\"incoming_rate\":0,\"item_tax_rate\":\"{}\",\"actual_batch_qty\":0,\"actual_qty\":0,\"serial_no\":null,\"batch_no\":null,\"sales_order\":null,\"so_detail\":null,\"sales_invoice_item\":null,\"delivery_note\":null,\"dn_detail\":null,\"delivered_qty\":0,\"purchase_order\":null,\"purchase_order_item\":null,\"location\":null,\"cost_center\":\"Main - 8D\",\"department\":null,\"project\":null,\"page_break\":0,\"parent\":\"ACC-SINV-2024-34770\",\"parentfield\":\"items\",\"parenttype\":\"Sales Invoice\",\"doctype\":\"Sales Invoice Item\",\"__unsaved\":1}],\"sales_team\":[],\"payment_schedule\":[{\"name\":\"90t5vvml9n\",\"owner\":\"Administrator\",\"creation\":\"2024-11-04 12:41:12.506877\",\"modified\":\"2024-11-04 12:41:12.506877\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":1,\"payment_term\":null,\"description\":null,\"due_date\":\"2024-11-04\",\"mode_of_payment\":null,\"invoice_portion\":100,\"discount_type\":null,\"discount_date\":null,\"discount\":0,\"payment_amount\":10000,\"outstanding\":10000,\"paid_amount\":0,\"discounted_amount\":0,\"base_payment_amount\":10000,\"parent\":\"ACC-SINV-2024-34770\",\"parentfield\":\"payment_schedule\",\"parenttype\":\"Sales Invoice\",\"doctype\":\"Payment Schedule\"}],\"packed_items\":[],\"taxes\":[],\"payments\":[],\"pricing_rules\":[{\"name\":\"90t5fikt8k\",\"owner\":\"Administrator\",\"creation\":\"2024-11-04 12:41:12.506211\",\"modified\":\"2024-11-04 12:41:12.506211\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":1,\"pricing_rule\":\"PRLE-0003\",\"item_code\":\"Crane\",\"margin_type\":null,\"rate_or_discount\":null,\"child_docname\":\"90t4e74198\",\"rule_applied\":1,\"parent\":\"ACC-SINV-2024-34770\",\"parentfield\":\"pricing_rules\",\"parenttype\":\"Sales Invoice\",\"doctype\":\"Pricing Rule Detail\"}],\"advances\":[],\"timesheets\":[],\"__onload\":{\"make_payment_via_journal_entry\":0},\"__last_sync_on\":\"2024-11-04T07:11:07.294Z\"}",
		"action": "Submit"
	},
	"btn": {
		"jQuery370029033430221278311": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 10427,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "InFailedSqlTransaction",
	"_exc_source": "assets (app)",
	"_debug_messages": "[\"Error in query:\\ncolumn \\\"department\\\" does not exist\\nLINE 1: SELECT \\\"department\\\" FROM \\\"tabAsset Depreciation Schedule\\\" WH...\\n               ^\\n\", \"Error in query:\\ncurrent transaction is aborted, commands ignored until end of transaction block\\n\", \"Error in query:\\ncurrent transaction is aborted, commands ignored until end of transaction block\\n\"]"
}
```
```

**Comment by deepdoshi79** [comment]
Functionality Working. Issue Resolved.
